
========================================================

This is the automated one for all tp and dose



```{r}
rm(list=ls())
setwd("D:/R_HOME/R_WORK/s1500 geneset")

#require(rat2302rnentrezg.db)
#require()

library(stringr)
library(ggplot2)


myPath <- "D:/R_HOME/R_WORK/mArray BAC reporter studie/results/unfiltered fold changes brainarray/PHH"
savePath <-"D:/R_HOME/R_WORK/s1500 geneset"
myFolders <- paste( myPath,dir( myPath ) , sep = "/" )
dir(myPath)
# gene set:
#gene.list.rd <- read.delim(
#  file= "D:/POC/POC meta analyse/full/figure 4/POC bacs rat.txt", sep ="\t", header = F)
#head(gene.list.rd)

dir()
#gene.list <- gene.list.rd[, "V2", drop =F]
gene.list <- c("140809", "1026", "1649")
  #read.table(file = "rat_orth.txt", sep = "\t" )
  #gene.list.rd[ gene.list.rd$type=="inflammatory",5]
#gene.list <- gene.list$rgd_symbol
head(gene.list)
length(gene.list) == length(unique(gene.list))
gene.list <- unique(gene.list)
gene.list<- as.character(gene.list)
#gene.list <- data.frame(V1=c( 55332))


head(gene.list)

# load all the data in 1 table
my.list = list()
n<-0
for (j in 1 : length(myFolders))
  {

  myFiles <-  dir(myFolders[j])

  for (i in 1: length( myFiles )) 
  {
  n <- n + 1
  
  buffer <- read.table( paste(myFolders[j], "/", myFiles[ i ], sep = ""), sep = ",", row.names = 1, header = TRUE )
  colnames(buffer)[colnames(buffer) == "entrez_ID"] <- "ENTREZID"

  zehGenesIndexes<-   buffer$ENTREZID %in%  gene.list
  zehGeneListPerCompound<-buffer[ zehGenesIndexes, ]
  
  naampje <- myFiles[i]
  naampje <- gsub("_rma_NF_.csv", "", naampje )
  my.dose <- str_match(naampje, "(_[HLMighowidle]{3,}_)"  )[1]
  my.dose <- gsub("_","", my.dose)
  my.time <- str_match(naampje, "_[0-9]{1,2}hr_")[1] # day_  #hr_
  my.time <- gsub("_","",my.time)
  my.treatment <- str_match(naampje,  "^([^_]*)")[1]
  
  zehGeneListPerCompound$dose <- my.dose
  zehGeneListPerCompound$time <- my.time
  zehGeneListPerCompound$treatment <- my.treatment
  head(zehGeneListPerCompound)
  my.list[[n]] <-  zehGeneListPerCompound
  rm("zehGeneListPerCompound","buffer", "zehGenesIndexes", "naampje", "my.dose", "my.time","my.treatment")
 print(paste("i is ", i, "j is ", j))
    }
}


output.df <- do.call('rbind', my.list)

setwd(savePath)
getwd()
output.df <- output.df[ !is.na(output.df$ENTREZID), ]
write.table(output.df, file = "DILI paper 3 genes.txt", sep ="\t",  row.names= T)

#### stop hier als geen plotjes wil


 output.df$dosetime <- paste(output.df$dose, output.df$time)
 output.df$dosetime<-factor(output.df$dosetime)
 output.df$treatment <- factor(output.df$treatment)
# 
 gene.list <- unique(output.df$ENTREZID)
# 
 head(output.df)



for ( j in 1 : length(gene.list) )
  {
 
  myGene <- output.df[output.df$ENTREZID == gene.list[ j ], ] 
pdf( paste(unique(myGene$symbols),"rat_single.pdf", sep = "_"), height = 40, width = 20  )
  
  head(myGene)
myGene$trick <- paste(myGene$treatment, myGene$dosetime)
                                                        
myGene$trick <- gsub("High 24hr", "H24", myGene$trick)
  myGene$trick <- gsub("High 8hr", "H8", myGene$trick)
  myGene$trick <- gsub("High 2hr", "H2", myGene$trick)
  myGene$trick <- gsub("Middle 24hr", "M24", myGene$trick)
  myGene$trick <- gsub("Middle 8hr", "M8", myGene$trick)
  myGene$trick <- gsub("Middle 2hr", "M2", myGene$trick)
  myGene$trick <- gsub("Low 24hr", "L24", myGene$trick)
  myGene$trick <- gsub("Low 8hr", "L8", myGene$trick)
  myGene$trick <- gsub("Low 2hr", "L2", myGene$trick)


myGene$trick <- gsub("High 9hr", "H9", myGene$trick)
  myGene$trick <- gsub("High 6hr", "H6", myGene$trick)
  myGene$trick <- gsub("High 3hr", "H3", myGene$trick)
  myGene$trick <- gsub("Middle 9hr", "M9", myGene$trick)
  myGene$trick <- gsub("Middle 6hr", "M6", myGene$trick)
  myGene$trick <- gsub("Middle 3hr", "M3", myGene$trick)
  myGene$trick <- gsub("Low 9hr", "L9", myGene$trick)
  myGene$trick <- gsub("Low 6hr", "L6", myGene$trick)
  myGene$trick <- gsub("Low 3hr", "L4", myGene$trick)


myGene$trick <- gsub("high 4 day", "H4d", myGene$trick)
  myGene$trick <- gsub("high 8 day", "H8d", myGene$trick)
  myGene$trick <- gsub("high 15 day", "H15d", myGene$trick)
  myGene$trick <- gsub("high 29 day", "H29d", myGene$trick)
  myGene$trick <- gsub("low 4 day", "L4d", myGene$trick)
  myGene$trick <- gsub("low 8 day", "L8d", myGene$trick)
  myGene$trick <- gsub("low 15 day", "L15d", myGene$trick)
  myGene$trick <- gsub("low 29 day", "L29d", myGene$trick)
  myGene$trick <- gsub("middle 4 day", "M4d", myGene$trick)
myGene$trick <- gsub("middle 8 day", "M8d", myGene$trick)
myGene$trick <- gsub("middle 15 day", "M15d", myGene$trick)
myGene$trick <- gsub("middle 29 day", "M29d", myGene$trick)



myGene$trick <- factor(myGene$trick)
ordered<-within(myGene, { trick <- reorder(trick, logFC )
                          })
position=position_dodge()

base <- ggplot(data=ordered, aes(x=trick, y=logFC)) + 
    geom_bar(
             size=0.3, stat="identity") +
      facet_wrap( ~dosetime , ncol=1, scales = "free_x") 


cbbPalette <- c("#0072B2", "#000000", "#AA00FFFF", "#D55E00", "#56B4E9", "#009E73", "#F0E442", "#CC79A7", "#E69F00", "darkgreen", "pink")


my.title <- unique(as.character(myGene$symbols))

base <- base +  xlab("DILI Compounds") + labs(y=expression(log[2](FC) ) ) + # Set axis labels
    ggtitle(paste ( my.title, sep = "-" )  )   # Set title
      
base <-  base + theme(axis.text.x = element_text( angle = 90, hjust = 1, vjust =0.5, size = 10, colour = "grey50"))  


print(base)


rm("myGene", "ordered")
 
  print(paste("compound printed to file: ", my.title))

dev.off()
}



# #       





```



wide format
```{r }
getwd()
m.data <- read.delim("rat_invivo_liver_repeated.txt", sep = "\t", header = T)
#m.data <- output.df
dir()
head(m.data)

m.data$treatment.dose.time <- paste(m.data$treatment, m.data$dose, m.data$time, sep =".")
m.data.s <- m.data[, c("logFC","symbols","ENTREZID","treatment.dose.time")]
head(m.data.s)

m.data.s$probeID <- rownames(m.data.s)
colnames(m.data.s)
#install.packages("reshape")
require(reshape)

test <- cast(m.data.s,   symbols  ~  treatment.dose.time , value = "logFC" )

test[1:10,1:5]
colnames(test)
dim(test)
sum(is.na(test))




#m.data.w <- reshape(m.data.s, v.names = c("treatment.dose.time" ),idvar ="ENTREZID", timevar="",  direction = "wide")
write.table(test, file = "PRH_wide data format.txt", sep = "\t", col.names=NA)
head(test)[,1:10]
?cast

?reshape

dim(m.data.w)

#selection wide format:
indwide24H <- grep(".High.24hr", colnames(test))
indwide8H <- grep(".High.8hr", colnames(test))
colnames(test)
data.24H <- test[,  indwide24H]
rownames(data.24H) <- test[, 'symbols']
data.8H <- test[, indwide8H]
rownames(data.8H) <- test[, 'symbols']

write.table(data.8H, file = "selection_8hours High dose.txt", sep = "\t", col.names=NA)
head(data.24H)[,1:5]
```


# bellow is a bit older code, might still be useable as template
```{r xmassTree}
rm(list=ls())
library(reshape)
library(ggplot2)
library(stringr)
#library(gdata)
myPath<-"/home/winks/R_HOME/R_WORK/Lisa mArray sept 2012/selected genes over all PHH mArrays/results/unfiltered FC and selections/high 24h vsnrma"
myGroups <- read.xls( file.path( "/home/winks/compounds for screen",  "TGPDrugsAnnotatedbyLabel_ForSteven.xls"), sep =",", header = T)
plotTitle <- "DILI_Severity_Genes_high_24hrs"
fileExt <- "_High_24hr_Control_24hr_vsnrma_.csv"


myFiles<- paste(myPath, dir(myPath), sep = "/")

myGroups <- subset( myGroups, select = c("Name_TGP","DILIConcern" ))
myGroups <- myGroups[myGroups$DILIConcern != "", ]

colnames(myGroups)<- c("compound", "DILIConcern")   
myGroups$DILIConcern <-factor(myGroups$DILIConcern)
myGroups$DILIConcern<-factor(myGroups$DILIConcern)
levels(myGroups$DILIConcern)
myGroups$DILIConcern<- gsub("Less-DILI-concern", "Less-DILI-Concern", myGroups$DILIConcern)
myGroups$DILIConcern<- gsub("Most-DILI-concern", "Most-DILI-Concern", myGroups$DILIConcern)
myGroups$DILIConcern<-factor(myGroups$DILIConcern)
levels(myGroups$DILIConcern)
head(myGroups)

myGroups$compound<-factor(myGroups$compound)

#gather data in 1 df

myList = list()
  for (i in 1 : length( myFiles ))
    {
    
    myList[[ i ]] <- read.delim( myFiles[i] , sep =",", header = T)
    myList[[ i ]]$variance <- apply(as.matrix(myList[[i]][,2]), MARGIN = 2, var )
    naamB <- gsub(paste( myPath, "/", sep =""), "", myFiles[ i ])
    naamBB<- gsub(fileExt, "", naamB)
    #naamBBB <- gsub( " ", "",  naamBB )
    #naamBBB <- gsub( "[% + -]", " ",  naamBB )
    #naamBBB <- gsub( ",", "",  naamBB )
    myList[[ i ]]$treatment <- naamBB
    myList[[ i ]] <- subset( myList[[ i ]], select = c("symbols", "logFC", "treatment", "variance"))
    ind <-  myGroups$compound %in% naamBB
    if ( sum( ind ) == 0)  
      {
        myList[[ i ]]$group <- "Unkown"
      
      } else if (sum( ind ) == 1)
        {
        myList[[ i ]]$group <- myGroups$DILIConcern[ ind]  
        } else
          {
            stop ( "mismatch")
          }
    }

  myDF <- do.call( "rbind", myList)
    
        myDFS <- subset(myDF, myDF$group != "Unkown" )
  head(myDF)        
head(myDFS)






#bellow is x-mass tree plotting

ordered <- within(myDFS, { treatment <-reorder(treatment, variance )
                                 group <- reorder(group, -variance)  })
colnames(ordered)



library(ggplot2)

library(RColorBrewer)
myColours <- rep(brewer.pal(8, "Set1"),10 )
length(myColours)
RColorBrewer::display.brewer.all()
cbbPalette <- c("#0072B2", "#000000", "#AA00FFFF", "#D55E00", "#56B4E9", "#009E73", "#F0E442", "#CC79A7", "#E69F00")
myColours <-rep(cbbPalette, 4 )
         length(myColours)       
myColours<-c(myColours, "#0072B2", "#000000", "#AA00FFFF")

groups <- qplot( logFC, treatment, data = ordered,  main = plotTitle)
groups <-groups + facet_grid(group ~ ., scales = "free",
space = "free") 
groups +  theme(strip.text.y = element_text(angle = 0))
?element_text

groups <- groups + aes(shape = symbols) + scale_shape_manual( values = c(25:1, 25:10 ) )  + aes(color = symbols) +
scale_color_manual( values = myColours ) 
groups <- groups + theme(strip.text.y = element_text(180))
groups + labs(x=expression(log[2](FC) ) )

groups + xlim(-2,2)

write.table(myDFS, file = paste("/home/winks/R_HOME/R_WORK/selections results march 2013/PHH/NRF2 NFkB and apoptosis summary","relaHits_screen_results.csv", sep = "/"), sep =",", col.names=NA)


groups <- groups + xlim(-2, 2.5)

groups


groups + aes( size = symbols ) + scale_size_manual( values = c(1, 1,2,1,1 ,rep(  1, 3 ), 1,1, 1,2,2,2,  rep(1,5),2, rep(1,12),1,1,2,1)    ) + aes(color = symbols) + scale_colour_manual(values = myColours) + aes(shape = symbols) + scale_shape_manual(values =c(25:1, 25:14  )  ) + coord_cartesian(xlim = c(-2,2))







groups <- qplot( logFC, treatment, data = ordered,  alpha=I(1/2), main = "TGP BAC PHH 24 hour high dose")
groups <-groups + facet_grid(group ~ ., scales = "free",
space = "free") + theme(strip.text.y = element_text())

library(RColorBrewer)
myColours <- rep(brewer.pal(8, "Set1"),5 )
RColorBrewer::display.brewer.all()

?brewer
groups + aes( size = symbols ) + scale_size_manual( values = c(1, 1,2,1,1 ,rep(  1, 3 ), 1,1, 1,2,2,2,  rep(1,5),2, rep(1,12),1,1,2,1)    ) + aes(color = symbols) + scale_colour_manual(values = myColours) + aes(shape = symbols) + scale_shape_manual(values =c(25:1, 25:14  )  ) + coord_cartesian(xlim = c(-2,2))

# 

#c("red", "orange", "blue", "green", "blue","red", "orange", "yellow", "green", "blue","red", "orange", "yellow", "green", "blue","red", "orange", "yellow", "green", "blue","red", "orange", "yellow", "green", "blue","red", "orange", "yellow", "green", "blue","red", "orange", "yellow", "green", "blue", "blue")








#ATF4 EIF4A1 EIF4A2 EIF4G3 HSPA5 XBP1 SRXN1 DDIT3
selGenes <- c("ATF4", "EIF4A1", "EIF4A2", "EIF4G3", "HSPA5", "XBP1", "SRXN1", "DDIT3")

for ( j in 1 : length(selGenes))
  {

  myGene <- subset( myDFS, myDFS$symbols == selGenes[ j ] )
  myGene <- subset( myGene, myGene$group != "No-DILI-Concern")

  ordered<-within(myGene, { treatment <-reorder(treatment, logFC )
                                 group <- reorder(group, -logFC)  })

base <- ggplot(data=ordered, aes(x=treatment, y=logFC, fill=group )) + 
    geom_bar(colour="white",
             position=position_dodge(),
             size=0.3, stat="identity") 


cbbPalette <- c("#0072B2", "#000000", "#AA00FFFF", "#D55E00", "#56B4E9", "#009E73", "#F0E442", "#CC79A7", "#E69F00")
base <- base  + scale_fill_manual(values=cbbPalette[c(3,7) ], name = "DILI-Severity") 
   

base <- base +  xlab("DILI Compounds") + labs(y=expression(log[2](FC) ) ) + # Set axis labels
    ggtitle(paste (plotTitle, selGenes[ j ], sep = "-" )  )   # Set title
      
base <-  base + theme(axis.text.x = element_text( angle = 90, hjust = 1, vjust =0.5, size = 10, colour = "grey50"))  

#pdf( paste( plotTitle, selGenes[j], sep = "-"), height = 10, width = 15  )
print(base)

dev.off()

}
geel
"#F0E442",
paars:
  "#AA00FFFF",

alsVoorbeeld <- c("#AA00FFFF","#AA00FFFF","#F0E442","#AA00FFFF","#AA00FFFF","#AA00FFFF","#F0E442","#F0E442","#F0E442","#AA00FFFF","#AA00FFFF","#F0E442","#F0E442","#F0E442","#F0E442","#F0E442","#F0E442","#F0E442","#AA00FFFF","#F0E442","#F0E442","#F0E442","#F0E442","#F0E442","#F0E442","#F0E442","#AA00FFFF","#F0E442","#F0E442","#AA00FFFF","#AA00FFFF","#F0E442","#F0E442","#F0E442","#F0E442","#F0E442","#F0E442",  "#AA00FFFF",  "#AA00FFFF","#F0E442","#AA00FFFF","#AA00FFFF","#AA00FFFF","#F0E442","#F0E442","#AA00FFFF","#AA00FFFF","#AA00FFFF","#AA00FFFF","#AA00FFFF","#AA00FFFF","#AA00FFFF","#AA00FFFF","#F0E442","#AA00FFFF","#AA00FFFF","#F0E442","#F0E442","#F0E442","#AA00FFFF","#F0E442","#F0E442","#F0E442","#AA00FFFF","#AA00FFFF","#AA00FFFF","#AA00FFFF","#F0E442","#AA00FFFF","#AA00FFFF","#F0E442","#F0E442","#F0E442","#F0E442","#AA00FFFF","#F0E442","#F0E442","#F0E442","#F0E442","#AA00FFFF","#AA00FFFF","#AA00FFFF","#AA00FFFF","#AA00FFFF","#F0E442","#F0E442","#F0E442","#F0E442","#AA00FFFF","#F0E442","#F0E442","#AA00FFFF","#AA00FFFF","#F0E442","#F0E442","#AA00FFFF","#F0E442","#AA00FFFF","#AA00FFFF")


alsVoorbeeld





#some older maybe usefull code snippets


#plot for lisa: number of compounds that induce at least e.g. 25% of genes at level fold change 2 per DILI group
head(myDFS)
length(unique(myDFS$treatment))
length(myDFS$treatment)

head(myData24hFC_long1)

condTest <- function(x) sum( x > log2(1.5) ) >5
myTest <- by( data=myData24hFC_long1$FC, FUN = condTest, INDICES = as.factor( myData24hFC_long1$Treatment ) ) 
sum(myTest)
class(myTest)
myTestDF<- as.data.frame(myTest[1 : length(unique(myData24hFC_long1$Treatment )) ])
myTestDF$treatment <- rownames(myTestDF)


ind<-match(unique(myData24hFC_long1$Treatment),myData24hFC_long1$Treatment)
aggr <- myData24hFC_long1[ind,]
nrow(aggr)==length(unique(myData24hFC_long1$Treatment))
colnames(aggr)[2]<-"treatment"
aggrE <-merge( x=myTestDF,y= aggr, by = "treatment" )    

colnames(aggrE)[2] <- "test"



aggrEL <- aggregate( test ~ group, data = aggrE,  sum    )



myF<-function(x) length(levels(factor(x)))
  toNorm <- by(data = myData24hFC_long1$Treatment, FUN =myF, INDICES = as.factor(myData24hFC_long1$group) )
    toNorm<-as.data.frame(toNorm[ 1 : length(unique(myData24hFC_long1$group ))])
      colnames(toNorm)<-"nCompounds"
aggrC<- cbind(aggrEL, toNorm)
aggrCS <- aggrC[-1,]    
  qplot(x = group, y = test/nCompounds, data = aggrCS) + geom_histogram(stat = "identity") 









g ordered_8h<-with(myData8hFC_long, reorder( Treatment , variance) );
g ordered_24h<-with(myData24hFC_long, reorder( Treatment , variance) );
change names
plot<-qplot( FC, ordered_8h, data = myData8hFC_long, fill = symbols, color = symbols, alpha=I(1/2) ) 
g plot<- plot + aes(shape = symbols) + scale_shape_manual( values = c(1:25, 1:9)) 
g plot <- plot + facet_grid(group ~ ., scales = "free",
g space = "free") + theme(strip.text.y = element_text())
g plot
last_plot() + aes( size = symbols ) + scale_size_manual( values = c(1, 1,3,1,1 ,rep(  1, 3 ), 1,1, 1,3,3,3,  rep(1,5),3, rep(1,12),1,1,3,1)    ) + aes(color = symbols) + scale_colour_manual(values = c("red", "orange", "yellow", "green", "blue","red", "orange", "yellow", "green", "blue","red", "orange", "yellow", "green", "blue","red", "orange", "yellow", "green", "blue","red", "orange", "yellow", "green", "blue","red", "orange", "yellow", "green", "blue","red", "orange", "yellow", "green", "blue", "blue"))
g plot<-qplot( FC, ordered_24h, data = myData24hFC_long, fill = symbols, color = symbols, alpha=I(1/2)  )
g plot<- plot + aes(shape = symbols) + scale_shape_manual( values = c(1:25, 1:9))
plot


```

